#!/usr/bin/env python3
"""
S3 バケット作成スクリプト（S3 ABAC 用）

Tenant A と Tenant B 用の S3 バケットを作成し、
オブジェクトタグ（tenant_id）を設定する。
"""

import boto3
import json
import os
import sys
import uuid
import argparse
from botocore.exceptions import ClientError

REGION = "us-east-1"
CONFIG_FILE = "phase11-config.json"


def get_account_id():
    """AWS アカウント ID を取得"""
    sts = boto3.client("sts", region_name=REGION)
    identity = sts.get_caller_identity()
    return identity["Account"]


def create_bucket(s3_client, bucket_name):
    """S3 バケットを作成"""
    try:
        if REGION == "us-east-1":
            s3_client.create_bucket(Bucket=bucket_name)
        else:
            s3_client.create_bucket(
                Bucket=bucket_name,
                CreateBucketConfiguration={"LocationConstraint": REGION},
            )
        print(f"[OK] Bucket created: {bucket_name}")
    except ClientError as e:
        if e.response["Error"]["Code"] in (
            "BucketAlreadyOwnedByYou",
            "BucketAlreadyExists",
        ):
            print(f"[INFO] Bucket already exists: {bucket_name}")
        else:
            raise


def upload_sample_objects(s3_client, bucket_name, tenant_id):
    """サンプルオブジェクトをアップロードし、テナントタグを設定"""
    objects = [
        {
            "key": f"data/{tenant_id}/report.txt",
            "body": f"Report for {tenant_id}\nGenerated by S3 ABAC example.",
        },
        {
            "key": f"data/{tenant_id}/invoice.csv",
            "body": f"invoice_id,amount,tenant\nINV-001,1000,{tenant_id}",
        },
    ]

    uploaded = []
    for obj in objects:
        s3_client.put_object(
            Bucket=bucket_name,
            Key=obj["key"],
            Body=obj["body"].encode("utf-8"),
        )
        print(f"[OK] Object uploaded: s3://{bucket_name}/{obj['key']}")

        # オブジェクトタグを設定
        s3_client.put_object_tagging(
            Bucket=bucket_name,
            Key=obj["key"],
            Tagging={
                "TagSet": [
                    {"Key": "tenant_id", "Value": tenant_id},
                ]
            },
        )
        print(f"[OK] Tag set: tenant_id={tenant_id} on {obj['key']}")
        uploaded.append(obj["key"])

    return uploaded


def save_config(config):
    """設定を JSON ファイルに保存"""
    with open(CONFIG_FILE, "w") as f:
        json.dump(config, f, indent=2)
    print(f"[OK] Configuration saved: {os.path.abspath(CONFIG_FILE)}")


def main():
    parser = argparse.ArgumentParser(description="S3 ABAC バケット作成スクリプト")
    parser.add_argument("--dry-run", action="store_true", help="実行せずに確認のみ")
    args = parser.parse_args()

    print("=" * 60)
    print("S3 ABAC Bucket Setup")
    print("=" * 60)

    account_id = get_account_id()
    print(f"[INFO] AWS Account: {account_id}")

    # バケット名にアカウント ID を含めてユニークにする
    suffix = account_id[-6:]
    bucket_name = f"s3-abac-example-{suffix}"

    print(f"[INFO] Bucket name: {bucket_name}")
    print(f"[INFO] Region: {REGION}")

    if args.dry_run:
        print("[INFO] Dry run mode - no resources will be created")
        print(f"  Bucket: {bucket_name}")
        print(f"  Tenant A objects: data/tenant-a/report.txt, data/tenant-a/invoice.csv")
        print(f"  Tenant B objects: data/tenant-b/report.txt, data/tenant-b/invoice.csv")
        return

    s3_client = boto3.client("s3", region_name=REGION)

    # Step 1: バケット作成
    print("\n[STEP 1] Creating S3 bucket...")
    create_bucket(s3_client, bucket_name)

    # Step 2: Tenant A のオブジェクトをアップロード
    print("\n[STEP 2] Uploading Tenant A objects...")
    objects_a = upload_sample_objects(s3_client, bucket_name, "tenant-a")

    # Step 3: Tenant B のオブジェクトをアップロード
    print("\n[STEP 3] Uploading Tenant B objects...")
    objects_b = upload_sample_objects(s3_client, bucket_name, "tenant-b")

    # Config 保存
    config = {
        "accountId": account_id,
        "region": REGION,
        "bucket": {
            "bucketName": bucket_name,
            "bucketArn": f"arn:aws:s3:::{bucket_name}",
        },
        "tenantA": {
            "tenantId": "tenant-a",
            "objects": objects_a,
        },
        "tenantB": {
            "tenantId": "tenant-b",
            "objects": objects_b,
        },
    }
    save_config(config)

    print("\n" + "=" * 60)
    print("[OK] S3 bucket setup complete!")
    print("=" * 60)
    print("\nNext steps:")
    print("  1. Run: python3 setup-iam-roles.py")
    print("  2. Run: python3 test-s3-abac.py")


if __name__ == "__main__":
    main()
